# Generated by Django 5.2.3 on 2025-06-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0002_author_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='created_at',
        ),
    ]
