# Generated by Django 5.2.3 on 2025-06-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0003_rename_pub_date_news_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news_.author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
