# Generated by Django 5.2.3 on 2025-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0005_author_last_name_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
