# Generated by Django 5.2.3 on 2025-10-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0007_user_remove_author_last_name_remove_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
