# Generated by Django 5.2.3 on 2025-10-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
