# Generated by Django 5.2.3 on 2025-10-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0009_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
