# Generated by Django 5.2.3 on 2025-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0012_alter_news_user_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default='news', max_length=100),
        ),
    ]
