# Generated by Django 5.2.3 on 2025-10-25 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0013_news_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('News', 'News'), ('Articles', 'Articles')], default='News', max_length=100),
        ),
    ]
