# Generated by Django 5.2.3 on 2025-10-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0014_news_subscribers_alter_news_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('News', 'Articles')], default='News', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.ForeignKey(default='News', on_delete=django.db.models.deletion.CASCADE, to='news_.category'),
        ),
    ]
