# Generated by Django 5.2.3 on 2025-10-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_', '0015_category_alter_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_.category'),
        ),
    ]
